name: '@ForesightMiningSoftwareCorporation/is-newer-version'
description: 'Compare semantic versions & detect updates by release type (major, minor, patch) - GitHub Action'
branding:
  icon: 'box'
  color: 'green'
author: 'ForesightMiningSoftwareCorporation'
inputs:
  before:
    required: true
    description: 'This input represents the original semantic version number to compare against. It should be provided as a string in the format "X.Y.Z" where X, Y, and Z are integers representing the major, minor, and patch versions respectively.'
  after:
    required: true
    description: 'This input represents the new semantic version number to compare against. It should be provided as a string in the same format as the before input.'
  release_type:
    required: false
    description: 'This input specifies the release type to use when comparing the two versions. It should be provided as a string that is either "major", "minor", or "patch". If "major" is selected, the action will consider any change in the major version number to be an update. If "minor" is selected, the action will consider changes in the major or minor version numbers to be an update. Finally, if "patch" is selected, the action will only consider changes in the patch version number to be an update.'
    default: 'patch'
outputs:
  newer:
    description: 'A boolean value indicating whether the after version is after the before version given the release type. This will be `true` if the after version is after the before version, and `false` otherwise.'
runs:
  using: 'node16'
  main: 'dist/index.js'
